name: Test

on: [push, pull_request]
permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - uses: foundry-rs/setup-snfoundry@v2
      - name: Run cairo tests
        run: snforge test
        working-directory: contracts
